import uuid

from pydantic import BaseModel, Field


class WebSocketTokenRequest(BaseModel):
    session_id: uuid.UUID = Field(description="Interview session id bound to websocket token.")


class StreamlitLaunchTokenRequest(BaseModel):
    launch_token: str = Field(min_length=20, description="Short-lived launch token generated by Streamlit.")


class AccessTokenResponse(BaseModel):
    access_token: str
    token_type: str = "Bearer"
    expires_in: int


class WebSocketTokenResponse(BaseModel):
    ws_token: str
    token_type: str = "Bearer"
    expires_in: int
    session_id: uuid.UUID
